### ISSUE TITLE
speccy lint throws an exception

### ISSUE THREAD

**Issue by dkarlovi** [wework/speccy#253] opened 2019-01-17 10:21 UTC
## Detailed description

```
$ docker run --rm --volume `pwd`:/app --workdir /app  wework/speccy:latest lint public/api/docs.json
/opt/speccy/lint.js:83
        const { context, lintResults } = _options;
                ^

TypeError: Cannot destructure property `context` of 'undefined' or 'null'.
    at validator.validate (/opt/speccy/lint.js:83:42)
    at /opt/speccy/node_modules/call-me-maybe/index.js:13:28
    at process.internalTickCallback (internal/process/next_tick.js:70:11)
```

## Context

Running speccy on CI.

## Your environment

- Docker 18.09.1
- Speccy Docker image `latest`, pulled just now.
- Valid Swagger 2.0 file (tested with `nktpro/swagger-cli`)
- no config file

**Comment by philsturgeon** [comment] 2019-01-17 14:18
Duplicate of #234

**Closed by philsturgeon** 2019-01-17 14:18 UTC

**Comment by philsturgeon** [comment] 2019-01-18 16:37
Please test this is working using v0.9.0-1:

```
npx speccy@0.9.0-1 lint foo.yaml
```

Please confirm if its working for you. If not, we need more tests :D
